// <auto-generated />
using System;
using DAL.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251025141316_FinalFixNormalizedEmail")]
    partial class FinalFixNormalizedEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("75e80354-8abf-4543-8db0-21a82c75389d"),
                            Author = "F. Scott Fitzgerald",
                            CategoryId = new Guid("bbd11a59-3e95-44b1-a1d0-a4a43a1b90e2"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2769),
                            ISBN = "9780743273565",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1925,
                            Rating = 5,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("0a37ee70-5cb9-45da-a398-0a29e7b3d8ac"),
                            Author = "Stephen Hawking",
                            CategoryId = new Guid("eb56fcf2-5240-49bc-8f48-40abfec5f889"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2774),
                            ISBN = "9780553380163",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1988,
                            Rating = 4,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = new Guid("d4b1823d-0673-4ee2-a62b-b7eafc9852e6"),
                            Author = "Yuval Noah Harari",
                            CategoryId = new Guid("004d4649-a7d4-4daa-88dd-a8449bf0f06f"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2777),
                            ISBN = "9780062316097",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 2011,
                            Rating = 5,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = new Guid("fabb41bd-4933-4262-aed7-1e1f25203bcc"),
                            Author = "Robert C. Martin",
                            CategoryId = new Guid("63e45c7b-cf5c-4443-8e5b-5333acb94ff0"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2780),
                            ISBN = "9780132350884",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 2008,
                            Rating = 5,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("94afa104-3de0-4bde-a2db-5ff87a883259"),
                            Author = "J.K. Rowling",
                            CategoryId = new Guid("2043e621-2dc8-4db6-a081-e6dbcf413657"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2783),
                            ISBN = "9780590353427",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1997,
                            Rating = 5,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = new Guid("62d544d8-48e0-4ecd-b251-22d4351c3759"),
                            Author = "Paulo Coelho",
                            CategoryId = new Guid("bbd11a59-3e95-44b1-a1d0-a4a43a1b90e2"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2785),
                            ISBN = "9780061122415",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1988,
                            Rating = 4,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = new Guid("0566ccc7-b261-4b09-9e34-55a8c8a9eb95"),
                            Author = "Cormen et al.",
                            CategoryId = new Guid("63e45c7b-cf5c-4443-8e5b-5333acb94ff0"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2787),
                            ISBN = "9780262033848",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 2009,
                            Rating = 5,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = new Guid("5fbdd974-d441-4ca7-96c6-5cd85af0a7c0"),
                            Author = "Charles Darwin",
                            CategoryId = new Guid("eb56fcf2-5240-49bc-8f48-40abfec5f889"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2790),
                            ISBN = "9781509827695",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1859,
                            Rating = 5,
                            Title = "The Origin of Species"
                        },
                        new
                        {
                            Id = new Guid("546ebec1-325a-4b91-b2f2-e4e3272b4e5f"),
                            Author = "H.G. Wells",
                            CategoryId = new Guid("004d4649-a7d4-4daa-88dd-a8449bf0f06f"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2795),
                            ISBN = "9780679405365",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1922,
                            Rating = 4,
                            Title = "World History"
                        },
                        new
                        {
                            Id = new Guid("791841ea-cd9d-412b-a60d-7ce1a728c94d"),
                            Author = "Roald Dahl",
                            CategoryId = new Guid("2043e621-2dc8-4db6-a081-e6dbcf413657"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2797),
                            ISBN = "9780142410318",
                            IsActive = true,
                            IsAvailable = true,
                            PublishedYear = 1964,
                            Rating = 5,
                            Title = "Charlie and the Chocolate Factory"
                        });
                });

            modelBuilder.Entity("DAL.Entities.BorrowingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FineAmount")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowingTransactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9197210a-1745-45e9-9556-864ff27eae74"),
                            BookId = new Guid("75e80354-8abf-4543-8db0-21a82c75389d"),
                            BorrowingDate = new DateTime(2025, 10, 20, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7440),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7538),
                            DueDate = new DateTime(2025, 10, 30, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7527),
                            FineAmount = 0m,
                            IsActive = true,
                            IsReturned = false,
                            MemberId = new Guid("ff87c8bf-d154-4ff6-95a3-f9c09ca528e4")
                        },
                        new
                        {
                            Id = new Guid("f86da3de-d8fc-4fde-bee6-8a1deab19964"),
                            BookId = new Guid("0a37ee70-5cb9-45da-a398-0a29e7b3d8ac"),
                            BorrowingDate = new DateTime(2025, 10, 22, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7544),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7559),
                            DueDate = new DateTime(2025, 11, 1, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7547),
                            FineAmount = 0m,
                            IsActive = true,
                            IsReturned = false,
                            MemberId = new Guid("cb20f41a-b8a6-421d-a642-8c8ee8fac706")
                        },
                        new
                        {
                            Id = new Guid("15bf177c-7b90-43d9-bf96-c13860b96c7f"),
                            BookId = new Guid("d4b1823d-0673-4ee2-a62b-b7eafc9852e6"),
                            BorrowingDate = new DateTime(2025, 10, 23, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7569),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7576),
                            DueDate = new DateTime(2025, 11, 2, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7572),
                            FineAmount = 0m,
                            IsActive = true,
                            IsReturned = false,
                            MemberId = new Guid("ff87c8bf-d154-4ff6-95a3-f9c09ca528e4")
                        },
                        new
                        {
                            Id = new Guid("56339d66-c89a-44ae-8529-f545760cdeb9"),
                            BookId = new Guid("62d544d8-48e0-4ecd-b251-22d4351c3759"),
                            BorrowingDate = new DateTime(2025, 10, 24, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7580),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7594),
                            DueDate = new DateTime(2025, 11, 3, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7588),
                            FineAmount = 0m,
                            IsActive = true,
                            IsReturned = false,
                            MemberId = new Guid("4d2fb760-5a96-478a-a376-8b104b1e7515")
                        },
                        new
                        {
                            Id = new Guid("e53a82fa-dbd9-41ad-84f5-9bddfac6d495"),
                            BookId = new Guid("0566ccc7-b261-4b09-9e34-55a8c8a9eb95"),
                            BorrowingDate = new DateTime(2025, 10, 18, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7682),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7689),
                            DueDate = new DateTime(2025, 10, 28, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7685),
                            FineAmount = 0m,
                            IsActive = true,
                            IsReturned = false,
                            MemberId = new Guid("537254e8-3e5d-41a5-a626-fe3c1c59d0e5")
                        },
                        new
                        {
                            Id = new Guid("d4aec383-4d05-4323-8d80-1b4591c41ad4"),
                            BookId = new Guid("fabb41bd-4933-4262-aed7-1e1f25203bcc"),
                            BorrowingDate = new DateTime(2025, 10, 21, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7725),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7732),
                            DueDate = new DateTime(2025, 10, 31, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(7728),
                            FineAmount = 0m,
                            IsActive = true,
                            IsReturned = false,
                            MemberId = new Guid("948f0ebc-3242-43c6-94a0-8a94221c2c6e")
                        });
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbd11a59-3e95-44b1-a1d0-a4a43a1b90e2"),
                            CategoryName = "Fiction",
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2371),
                            Description = "Novels and stories",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("eb56fcf2-5240-49bc-8f48-40abfec5f889"),
                            CategoryName = "Science",
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2426),
                            Description = "Science books",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("004d4649-a7d4-4daa-88dd-a8449bf0f06f"),
                            CategoryName = "History",
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2428),
                            Description = "Historical books",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("63e45c7b-cf5c-4443-8e5b-5333acb94ff0"),
                            CategoryName = "Technology",
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2433),
                            Description = "Tech & Programming",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("2043e621-2dc8-4db6-a081-e6dbcf413657"),
                            CategoryName = "Children",
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2435),
                            Description = "Kids books",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DAL.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MembershipEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff87c8bf-d154-4ff6-95a3-f9c09ca528e4"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2900),
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            IsActive = true,
                            MembershipEndDate = new DateTime(2026, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2898),
                            MembershipStartDate = new DateTime(2024, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2891),
                            Phone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("cb20f41a-b8a6-421d-a642-8c8ee8fac706"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2905),
                            Email = "bob@example.com",
                            FullName = "Bob Smith",
                            IsActive = true,
                            MembershipEndDate = new DateTime(2026, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2904),
                            MembershipStartDate = new DateTime(2024, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2902),
                            Phone = "01087654321"
                        },
                        new
                        {
                            Id = new Guid("948f0ebc-3242-43c6-94a0-8a94221c2c6e"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2910),
                            Email = "charlie@example.com",
                            FullName = "Charlie Brown",
                            IsActive = true,
                            MembershipEndDate = new DateTime(2026, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2909),
                            MembershipStartDate = new DateTime(2024, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2907),
                            Phone = "01055555555"
                        },
                        new
                        {
                            Id = new Guid("4d2fb760-5a96-478a-a376-8b104b1e7515"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2915),
                            Email = "diana@example.com",
                            FullName = "Diana Prince",
                            IsActive = true,
                            MembershipEndDate = new DateTime(2026, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2913),
                            MembershipStartDate = new DateTime(2024, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2912),
                            Phone = "01099988877"
                        },
                        new
                        {
                            Id = new Guid("537254e8-3e5d-41a5-a626-fe3c1c59d0e5"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2919),
                            Email = "edward@example.com",
                            FullName = "Edward King",
                            IsActive = true,
                            MembershipEndDate = new DateTime(2026, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2918),
                            MembershipStartDate = new DateTime(2024, 10, 25, 17, 13, 14, 964, DateTimeKind.Local).AddTicks(2916),
                            Phone = "01011223344"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ReservationTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("ReservationTransactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("81f795ae-a95f-4ab2-93a6-2ff6e558235c"),
                            BookId = new Guid("5fbdd974-d441-4ca7-96c6-5cd85af0a7c0"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8446),
                            DueDate = new DateTime(2025, 11, 1, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8442),
                            IsActive = true,
                            MemberId = new Guid("ff87c8bf-d154-4ff6-95a3-f9c09ca528e4"),
                            ReservationDate = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8432)
                        },
                        new
                        {
                            Id = new Guid("78c492dc-ab64-4299-90d2-5eff2178dde9"),
                            BookId = new Guid("546ebec1-325a-4b91-b2f2-e4e3272b4e5f"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8457),
                            DueDate = new DateTime(2025, 11, 1, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8454),
                            IsActive = true,
                            MemberId = new Guid("cb20f41a-b8a6-421d-a642-8c8ee8fac706"),
                            ReservationDate = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8451)
                        },
                        new
                        {
                            Id = new Guid("8502c8ab-6f93-4e94-b004-e93543a2a8e4"),
                            BookId = new Guid("791841ea-cd9d-412b-a60d-7ce1a728c94d"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8468),
                            DueDate = new DateTime(2025, 11, 1, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8464),
                            IsActive = true,
                            MemberId = new Guid("948f0ebc-3242-43c6-94a0-8a94221c2c6e"),
                            ReservationDate = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8461)
                        },
                        new
                        {
                            Id = new Guid("8fe63b46-bb3c-4cec-a659-b3ea695b9ec2"),
                            BookId = new Guid("94afa104-3de0-4bde-a2db-5ff87a883259"),
                            CreatedOn = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8485),
                            DueDate = new DateTime(2025, 11, 1, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8474),
                            IsActive = true,
                            MemberId = new Guid("4d2fb760-5a96-478a-a376-8b104b1e7515"),
                            ReservationDate = new DateTime(2025, 10, 25, 17, 13, 15, 315, DateTimeKind.Local).AddTicks(8471)
                        });
                });

            modelBuilder.Entity("DAL.Extend.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-0001",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user-0002",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("DAL.Extend.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAgree")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5bd7796f-c987-4036-ac6f-42c3e34dfca3",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsAgree = false,
                            LockoutEnabled = false,
                            MemberId = new Guid("ff87c8bf-d154-4ff6-95a3-f9c09ca528e4"),
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEF7AhjwK0G2BcYwFV3zsgvF9bE8E7enf2bMmcbnnFDXZBu3si2tfzOUT1lqDvY71lQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "734c744f-76cd-4325-96da-163993c0d230",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "user-0002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c6e5c16-5a88-4474-97e8-36f9afd67697",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsAgree = false,
                            LockoutEnabled = false,
                            MemberId = new Guid("cb20f41a-b8a6-421d-a642-8c8ee8fac706"),
                            NormalizedEmail = "BOB@GMAIL.COM",
                            NormalizedUserName = "BOB",
                            PasswordHash = "AQAAAAIAAYagAAAAEOqDTInxyPJuB2scRgpzf2Rd7xfEoI4y0QtBa221F+MyoLpi42eZZPJz62VDbFUuhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1e205f3-0458-468e-b8d2-924dfd66613c",
                            TwoFactorEnabled = false,
                            UserName = "bob"
                        },
                        new
                        {
                            Id = "user-0003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bbd89e4e-6455-434a-a49f-b34ed640f162",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsAgree = false,
                            LockoutEnabled = false,
                            MemberId = new Guid("948f0ebc-3242-43c6-94a0-8a94221c2c6e"),
                            NormalizedEmail = "CHARLIE@GMAIL.COM",
                            NormalizedUserName = "CHARLIE",
                            PasswordHash = "AQAAAAIAAYagAAAAECEMInKpAySLzRYUJFGXPw5gjcZiy/VpR532slT7gz6HlEwxzs5RHeeFPAMPUntGgg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b7c6e0bd-86c0-4093-a33c-be4eddf9ab7f",
                            TwoFactorEnabled = false,
                            UserName = "charlie"
                        },
                        new
                        {
                            Id = "user-0004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11e73202-b94a-47ea-9917-58e1e6be732e",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsAgree = false,
                            LockoutEnabled = false,
                            MemberId = new Guid("4d2fb760-5a96-478a-a376-8b104b1e7515"),
                            NormalizedEmail = "DIANA@GMAIL.COM",
                            NormalizedUserName = "DIANA",
                            PasswordHash = "AQAAAAIAAYagAAAAEJZSiAxPQScH8spuyH5qhOYfoJO0h7a+rquPrrNGRDKRV1GLVEar6Hs1c7GdLeztWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65ec612e-5328-4f65-8ac0-0fa116de3571",
                            TwoFactorEnabled = false,
                            UserName = "diana"
                        },
                        new
                        {
                            Id = "user-0005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d3648a1-4c02-437b-8f82-5afcb27d3b3d",
                            CreatedOn = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "edward@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsAgree = false,
                            LockoutEnabled = false,
                            MemberId = new Guid("537254e8-3e5d-41a5-a626-fe3c1c59d0e5"),
                            NormalizedEmail = "EDWARD@GMAIL.COM",
                            NormalizedUserName = "EDWARD",
                            PasswordHash = "AQAAAAIAAYagAAAAEPuCgQLXZc7JqjrNPFYHmgr2R1RMvMB68usYIwQjvIlS9nQ5THLnLyKYRW3KkII+bQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3834a959-77a1-47c6-af18-77b4abf96de8",
                            TwoFactorEnabled = false,
                            UserName = "edward"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-0001",
                            RoleId = "role-admin-0001"
                        },
                        new
                        {
                            UserId = "user-0002",
                            RoleId = "role-user-0002"
                        },
                        new
                        {
                            UserId = "user-0003",
                            RoleId = "role-user-0002"
                        },
                        new
                        {
                            UserId = "user-0004",
                            RoleId = "role-user-0002"
                        },
                        new
                        {
                            UserId = "user-0005",
                            RoleId = "role-user-0002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Book", b =>
                {
                    b.HasOne("DAL.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DAL.Entities.BorrowingTransaction", b =>
                {
                    b.HasOne("DAL.Entities.Book", "Book")
                        .WithMany("BorrowingTransactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Member", "Member")
                        .WithMany("BorrowingTransactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.Entities.ReservationTransaction", b =>
                {
                    b.HasOne("DAL.Entities.Book", "Book")
                        .WithMany("ReservationTransactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Member", "Member")
                        .WithMany("ReservationTransactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.Extend.ApplicationUser", b =>
                {
                    b.HasOne("DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DAL.Extend.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DAL.Extend.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Extend.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.Book", b =>
                {
                    b.Navigation("BorrowingTransactions");

                    b.Navigation("ReservationTransactions");
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Entities.Member", b =>
                {
                    b.Navigation("BorrowingTransactions");

                    b.Navigation("ReservationTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
